### ISSUE TITLE
About the hyperspherical distance distributions

### ISSUE THREAD

**Issue by myt889** [chengtan9907/Hyperspherical-Consistency-Regularization#1]
Hi, Cheng Tan,
      Thanks for sharing such an interesting work. Recently, I have similar work with HCR, and I want to know how I can obtain the figure like Figure 6 in your paper, I mean the hyperspherical distance distributions of the CIFAR-10 dataset with 80% symmetric noise. Thank you so much, if you can share the code or give me some guidance.  My e-mail: myt889@163.com

Best regards,
Tan

**Comment by chengtan9907** [comment]
I will close this issue if there is no more question. Please feel free to open a new issue when you have new questions.
